import Foundation
import Testing

// The Info.plist is generated by a heredoc in scripts/bundle.sh rather than
// checked in, so the only place to guard its keys is the script itself.

private func bundleScriptSource() throws -> String {
    let repoRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent() // macshotTests
        .deletingLastPathComponent() // Tests
        .deletingLastPathComponent() // repo root
    return try String(
        contentsOf: repoRoot.appendingPathComponent("scripts/bundle.sh"),
        encoding: .utf8
    )
}

@Test
func theBundleDeclaresItselfAUIElementSoNoDockIconAppears() throws {
    let script = try bundleScriptSource()
    #expect(
        script.contains("<key>LSUIElement</key>"),
        "macshot is a menu bar utility: without LSUIElement it gets a Dock tile and a Cmd-Tab entry"
    )
    // The key only counts when it is actually true.
    let afterKey = script.components(separatedBy: "<key>LSUIElement</key>")[1]
    #expect(afterKey.trimmingCharacters(in: .whitespacesAndNewlines).hasPrefix("<true/>"))
}

// TCC keeps one Screen Recording grant per bundle identifier and pins it to the
// signature, and it names the app in System Settings after the bundle's file
// name. Dev and release builds are signed differently, so sharing either would
// make each build invalidate the other's grant — or, sharing only the file
// name, leave two indistinguishable rows behind.

@Test
func devAndReleaseBundlesCannotBeMistakenForEachOther() throws {
    let script = try bundleScriptSource()
    #expect(script.contains("bundle_id=\"dev.macshot.app\""))
    #expect(script.contains("bundle_id=\"dev.macshot.app.debug\""))
    #expect(script.contains("app_name=\"macshot\""))
    #expect(script.contains("app_name=\"macshot-debug\""))
    // release.sh signs, notarizes and packages dist/macshot.app by that name.
    #expect(script.contains("app_path=\"$repo_root/dist/$app_name.app\""))
}
