import Foundation
import Testing

// The Info.plist is generated by a heredoc in scripts/bundle.sh rather than
// checked in, so the only place to guard its keys is the script itself.

private func bundleScriptSource() throws -> String {
    let repoRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent() // macshotTests
        .deletingLastPathComponent() // Tests
        .deletingLastPathComponent() // repo root
    return try String(
        contentsOf: repoRoot.appendingPathComponent("scripts/bundle.sh"),
        encoding: .utf8
    )
}

@Test
func theBundleDeclaresItselfAUIElementSoNoDockIconAppears() throws {
    let script = try bundleScriptSource()
    #expect(
        script.contains("<key>LSUIElement</key>"),
        "macshot is a menu bar utility: without LSUIElement it gets a Dock tile and a Cmd-Tab entry"
    )
    // The key only counts when it is actually true.
    let afterKey = script.components(separatedBy: "<key>LSUIElement</key>")[1]
    #expect(afterKey.trimmingCharacters(in: .whitespacesAndNewlines).hasPrefix("<true/>"))
}
